[package]
name = "filen-sdk-rs-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
default = []
tokio = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "visit-mut", "fold"] }
