name: CLI Bug Report
description: File a bug report about the Filen CLI v0.2.3 or later
title: ""
labels: ["cli", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: This form only supports **v0.2.3 and later**.
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - "win-x64"
        - "win-arm64"
        - "linux-x64"
        - "linux-arm64"
        - "macos-x64"
        - "macos-arm64"
        - "docker linux/x64"
        - "docker linux/arm64"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened and how?
      description: A clear and concise description of what happened and steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: A description of what the intended behaviour is.
    validations:
      required: true
  - type: textarea
    id: environment-details-and-context
    attributes:
      label: Additional environment details and context
      description: |
        Any other relevant environment details, e.g. hardware (CPU, RAM, disk, ...), VPN or proxy usage, filesystem and disk type used (e. g. SSD, NFTS, ext4)...
        Any other context about the problem that may be relevant...
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. 
        Please add the `-vvv` flag to increase verbosity and redact any sensitive information.
      render: shell
