use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::CommandFactory;
use filen_macros::extract_cli_doc_fragments;
use serde::Deserialize;

use crate::CliArgs;

extract_cli_doc_fragments!();

// markdown docs

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum MdDocElement {
	Heading { heading: u8, text: String },
	DocFragment { fragment_id: String },
	CommandHelp { command: String },
}

#[derive(Debug, Deserialize)]
struct MdDocFile {
	filename: String,
	title: String,
	elements: Vec<MdDocElement>,
}

#[derive(Debug, Deserialize)]
struct MdDocOutline {
	files: Vec<MdDocFile>,
}

/// This function generates documentation for the CLI in markdown format.
/// It reads the outline of the documentation (none of the text!) from a YAML file,
/// then fills in the actual documentation content from the CLI doc fragments,
/// and the command help texts generated by clap.
/// The doc fragments are doc comments in the source code marked with
/// `//! [filen-cli-doc] <fragment-id>`, right next to the code they document.
pub(crate) fn generate_markdown_docs() -> Result<()> {
	let mut commands = CliArgs::command();
	let cli_doc_fragments = get_cli_doc_fragments();

	let markdown_structure_source = include_str!("../docs/markdown_docs_outline.yaml");
	let markdown_structure = serde_yaml::from_str::<MdDocOutline>(markdown_structure_source)
		.context("Failed to parse markdown docs outline")?;

	let output_dir = PathBuf::from("filen-cli-markdown-docs");
	std::fs::create_dir_all(&output_dir).context("Failed to create markdown docs output dir")?;

	for doc_file in markdown_structure.files {
		let elements = doc_file
			.elements
			.iter()
			.map(|element| match element {
				MdDocElement::Heading { heading, text } => {
					Ok(format!("{} {}", "#".repeat((heading + 1) as usize), text))
				}
				MdDocElement::DocFragment { fragment_id } => {
					if let Some(fragment) = cli_doc_fragments
						.iter()
						.find(|fragment| fragment.id == *fragment_id)
					{
						Ok(fragment.content.to_string())
					} else {
						Err(anyhow::anyhow!(
							"Doc fragment with id '{}' not found",
							fragment_id
						))
					}
				}
				MdDocElement::CommandHelp { command } => {
					if let Some(command) = commands.find_subcommand_mut(command) {
						Ok(format!("```\n{}\n```", command.render_long_help()))
					} else {
						Err(anyhow::anyhow!(
							"Command '{}' not found in CLI structure",
							command
						))
					}
				}
			})
			.collect::<Result<Vec<String>>>()?;
		let mut markdown_content = String::new();
		markdown_content.push_str(&format!("# {}\n\n", doc_file.title));
		markdown_content.push_str(&elements.join("\n\n"));
		std::fs::write(output_dir.join(doc_file.filename.clone()), markdown_content).with_context(
			|| format!("Failed to write markdown doc file '{}'", doc_file.filename),
		)?;
	}
	Ok(())

	// todo: ensure sure no doc fragments or commands are unused
}
